List<String> awesomeQuotes = [
  "Life is 10% what happens to you and 90% how you react to it.- Charles R. Swindoll",
  "Change your thoughts, and you change your world.— Norman Vincent Peale",
  "All our dreams can come true if we have the courage to pursue them.- Walt Disney",
  "Success is a journey not a destination.- Ben Sweetland",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.- Zig Ziglar",
  "It always seems impossible until it's done.- Nelson Mandela",
  "Success is liking yourself, liking what you do, and liking how you do it.- Maya Angelou",
  "Aim for the moon. If you miss, you may hit a star.- W. Clement Stone",
  "If you cannot do great things, do small things in a great way.- Napoleon Hill",
  "Success only comes to those who dare to attempt.- Mallika Tripathi",
  "I never dreamed about success. I worked for it.- Estée Lauder",
  "If opportunity doesn't knock, build a door.- Milton Berle",
  "You’ve got to learn to leave the table when love’s no longer being served.- Nina Simone",
  "Scarcity of self-value cannot be remedied by money, recognition, affection, attention, or influence.- Gary Zukav",
  "Talk to yourself like someone you love.- Brené Brown",
  "Love yourself first and everything else falls into place.- Lucille Ball",
  "If you prioritize yourself, you are going to save yourself.- Gabrielle Union",
  "It takes courage to grow up and become who you really are.- E.E. Cummings",
  "You are your best thing.- Toni Morrison",
  "By being yourself you put something wonderful in the world that was not there before.- Edwin Elliot",
  "Caring for myself is not self-indulgence, it is self-preservation, and that is an act of political warfare.- Audre Lorde",
  "I realized that I don’t have to be perfect. All I have to do is show up and enjoy the messy, imperfect, and beautiful journey of my life.- Kerry Washington",
  "If we give our children sound self-love, they will be able to deal with whatever life puts before them.”- Bell Hooks",
  "Your talent is God's gift to you. What you do with it is your gift back to God.- Leo Buscaglia",
  "Be a first-rate version of yourself, instead of a second-rate version of somebody else.- Judy Garland",
  "For every minute you are angry, you lose sixty seconds of happiness.- Ralph Waldo Emerson",
  "There is only one happiness in this life: to love and be loved.- George Sand",
  "Joy does not simply happen to us. We have to choose joy and keep choosing it every day.- Henri J.M. Nouwen",
  "Be happy for this moment. This moment in your life.- Omar Khayyam",
  "If you carry joy in your heart, you can heal any moment.- Carlos Santana",
  "Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.- Thich Nhat Hanh",
  "Nothing is impossible. The word itself says, 'I'm possible!'- Audrey Hepburn",
  "If you can dream it, you can do it.- Walt Disney",
  "To live is the rarest thing in the world. Most people just exist.- Oscar Wilde",
  "Do something wonderful, people may imitate it.- Albert Schweitzer",
  "Those who bring sunshine into the lives of others cannot keep it from themselves.- J.M. Barrie",
  "To improve is to change; to be perfect is to change often.-Winston Churchill",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude.- Oprah Winfrey",
  "Everyone thinks of changing the world, but no one thinks of changing himself.- Leo Tolstoy",
  "Life isn't about finding yourself. Life is about creating yourself.- George Bernard Shaw",
  "You are never too old to set another goal or to dream a new dream.- C.S. Lewis",
  "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.- Helen Keller",
  "Rise above the storm and you will find the sunshine.- Mario Fernández",
  "Vitality shows not only in the ability to persist but in the ability to start over.- F. Scott Fitzgerald",
  "It is never too late to be what you might have been.- George Eliot",
  "You must be the change you wish to see in the world.- Mahatma Ghandi",
  "Mistakes are a fact of life. It is the response to the errors that counts.- Nikki Giovanni",
  "The only person you are destined to become is the person you decide to be.- Ralph Waldo Emerson",
  "You can't cross the sea merely by standing and staring at the water.- Rabindranath Tagore",
  "Life shrinks or expands in proportion to one’s courage.- Anaïs Nin",
  "The best way out is always through.- Robert Frost",
  "Courage doesn’t always roar. Sometimes, courage is the quiet voice at the end of the day saying, ‘I will try again tomorrow’.- Mary Anne Radmacher",
  "Doubt kills more dreams than failure ever will.- Suzy Kassem",
  "With the new day comes new strength and new thoughts.- Eleanor Roosevelt",
  "The moment you doubt whether you can fly, you cease forever to be able to do it.- J.M. Barrie",
  "You don't always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens.- Mandy Hale",
  "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.- Neil Gaiman",
  "What we fear of doing most is usually what we most need to do.- Ralph Waldo Emerson",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.- Winston S. Churchill",
  "It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest.- Walter Anderson",
  "Above all, be the heroine of your life, not the victim.- Nora Ephron",
  "inspirational quotes dodinskyWoman's Day/Getty Images",
  "Inspirational Quotes About Friendship and Love",
  "Be there for others, but never leave yourself behind.- Dodinsky",
  "True friendship is like a rose. We don’t realize its beauty until it fades.- Evelyn Loeb",
  "Let us always meet each other with a smile, for the smile is the beginning of love.- Mother Teresa",
  "When you put love out in the world it travels, and it can touch people and reach people in ways that we never even expected.- Laverne Cox",
  "Things are never quite as scary when you've got a best friend.- Bill Watterson",
  "Never regret anything that made you smile.- Mark Twain",
  "Try to be a rainbow in someone's cloud.- Maya Angelou",
  "The best and most beautiful things in the world cannot be seen or even touched- they must be felt with the heart.- Helen Keller",
  "Love doesn't make the world go 'round. Love is what makes the ride worthwhile.- Franklin P. Jones",
  "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: Only love can do that.- Martin Luther King Jr.",
  "When we strive to become better than we are, everything around us becomes better too.- Paulo Coelho",
  "Give light and people will find the way.- Ella Baker",
  "Be yourself; everyone else is already taken.- Oscar Wilde",
  "Don’t compromise yourself. You’re all you’ve got.- Janis Joplin",
  "Follow your heart. Listen to your inner voice. Stop caring about what others think.— Roy T. Bennett",
  "A girl should be two things: who and what she wants.- Coco Chanel",
  "You can’t be hesitant about who you are.- Viola Davis",
  "You’ve gotta dance like there’s nobody watching, love like you’ll never be hurt, sing like there’s nobody listening, and live like it’s heaven on earth.- William W. Purkey",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.- Mahatma Gandhi",
  "Imperfection is beauty, madness is genius and it’s better to be absolutely ridiculous than absolutely boring.- Marilyn Monroe",
  "Everything you can imagine is real.- Pablo Picasso",
  "Do what you can, with what you have, where you are.- Theodore Roosevelt",
  "A person who never made a mistake never tried anything new.- Albert Einstein",
  "Speak your mind, even if your voice shakes.- Maggie Kuhn",
  "Encourage yourself, believe in yourself, and love yourself. Never doubt who you are.- Stephanie Lahart",
  "The individual who says it is not possible should move out of the way of those doing it.- Trivia Cunningham",
  "You do not find the happy life. You make it.- Camilla Eyring Kimball",
  "Stay close to anything that makes you glad you are alive.- Hafez",
  "Keep your face to the sunshine and you cannot see a shadow.- Helen Keller",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character.- Unknown",
  "It is better to travel well than to arrive.- Buddha",
  "Wherever you go, go with all your heart.- Confucius",
  "Look deep into nature, and then you will understand everything better.- Albert Einstein",
  "A problem is a chance for you to do your best.- Duke Ellington",
  "Don’t count the days, make the days count.- Muhammad Ali",
  "Fall 7 times, stand up 8.- Japanese Proverb",
  "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.- George Lorimer",
  "In three words I can sum up everything I've learned about life: It goes on.- Robert Frost",
  "Some women choose to follow men, and some choose to follow their dreams. If you’re wondering which way to go, remember that your career will never wake up and tell you that it doesn’t love you anymore.- Lady Gaga",
  "Life is short, and it is here to be lived.- Kate Winslet",
  "No matter what happens in life, be good to people. Being good to people is a wonderful legacy to leave behind.- Taylor Swift",
  "If you risk nothing, then you risk everything.- Geena Davis",
  "Don’t waste a minute not being happy. If one window closes, run to the next window- or break down a door.- Brooke Shields",
  "Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness.- Oprah Winfrey",
  "The only way to have a life is to commit it to like crazy.- Angelina Jolie",
  "Believe in yourself. Stay in your own lane. There’s only one you.- Queen Latifah",
  "Miracles happen everyday, change your perception of what a miracle is and you'll see them all around you.- Jon Bon Jovi",
  "I was built this way for a reason, so I’m going to use it.- Simone Biles",
  "I have standards I don’t plan on lowering for anybody, including myself.- Zendaya",
  "Self-esteem means knowing you are the dream.- Oprah Winfrey",
  "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.- Steve Jobs",
  "A person without regrets is a nincompoop.- Mia Farrow",
  "If at first you don’t succeed, then skydiving definitely isn’t for you.- Steven Wright",
  "I always wanted to be somebody, but now, I realize I should have been more specific.- Lily Tomlin",
  "Don’t worry about the world coming to an end today. It is already tomorrow in Australia.- Charles Schulz",
  "Real courage is when you know you’re licked before you begin, but you begin anyway and see it through no matter what.- Harper Lee",
  "You can’t turn back the clock. But you can wind it up again.- Bonnie Prudden",
  "It’s a whole lot more satisfying to reach for the stars, even if you end up landing only on the moon.- Kermit the Frog",
  "Be open to learning new lessons, even if they contradict the lessons you learned yesterday.- Ellen Degeneres",
  "The sky isn’t the limit- the sky has no limit.- Sarah Barker",
  "They always say time changes things, but you actually have to change them yourself.- Andy Warhol",
  "The road to success and the road to failure are almost exactly the same.- Colin R. Davis",
  "Yesterday's the past, tomorrow's the future, but today is a gift. That's why it's called the present.- Bil Keane",
  "It is better to fail in originality than to succeed in imitation.- Herman Melvil",
];

List<String> articleTitle = [
  "Do they even need to fight for equality?",
  "Is the new age of cinematic really promoting feminism?",
  "Fortune female 500",
  "1900s and 2000s women empowerment",
];

List<String> imageUrl = [
  "https://media.istockphoto.com/photos/silhouette-of-super-strong-successful-businesswoman-picture-id1249879109?k=20&m=1249879109&s=612x612&w=0&h=I-joEMjqkq1wCJZJeLWUCd1d2HcB5WxBShdkA9YM0cg=",
  "https://media.istockphoto.com/vectors/young-woman-looks-at-the-mirror-and-sees-her-happy-reflection-vector-id1278815846?k=20&m=1278815846&s=612x612&w=0&h=JUTmV9Of-_ILOfXBfV9Cmp_41yuTliSdFIcZy5LKuss=",
  "https://media.istockphoto.com/vectors/mental-health-or-psychology-concept-with-flowering-human-head-vector-id1268669581?k=20&m=1268669581&s=612x612&w=0&h=YVLTKCZXKugEn40aqOkir4vcoFeTUAQToa1i3AFYRNU=",
  "https://media.istockphoto.com/photos/confidence-and-strength-concept-picture-id1086700012?k=20&m=1086700012&s=612x612&w=0&h=1wWVN3AB7BH7o3y2A2b-NG3HB9H6Dwkc9OLz2lxgwAY=",
];
